platform :ios, '11.0'
inhibit_all_warnings!

target 'MVCMessageComposer' do
  use_frameworks!

  pod 'Intrepid'
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftSpinner'

  target 'MVCMessageComposerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
